### ISSUE TITLE
I forked this repo to make changes, but the Wiki Pages didn't fork so I can't add to this page.

### ISSUE THREAD

**Issue by OXT-OpenXTalk** [macMikey/LCB-missing-manual#52]
I forked this repo to make changes, but the Wiki Pages didn't fork so I can't add to this page.

I was just going to add the undocumented LCB property metadata '_IDE'

This property indicates that the LCB module was included in the IDE

metadata _ide is "true"  -- the widget will not be removable from the Extension Manager stack contextual menu

**Comment by macMikey** [comment]
adding you to the collaborators. feel free to add and update the wiki.

**Comment by macMikey** [comment]
reopened until we update the wiki so we don't forget

**Comment by OXT-OpenXTalk** [comment]
OK great, but I'd rather you add @PaulMcClernan instead as I don't normally use this GitHub account for daily use.
Another 'missing manual' topic to cover could be on how to mimic 'classic controls' props in LCB Widgets as that can be a be a bit prickly.

**Comment by macMikey** [comment]
collab added.
i'm not sure what you mean by mimicing them, but why not throw up an issue and then explain.

**Comment by PaulMcClernan** [comment]
> collab added.

Thanks
I meant that sometimes, for whatever reason (bug?) you can't use the same name in your widget as one of the standard classic controls properties, or other issues like needing to expand the widgets bounding box for a shadow to not get clipped. They have made changes to the commercial LiveCode since what I'm using (OpenXtalk mod based on LCC 9.6.3), something about bounding boxes in LCB was changed I believe LC Ltd. announced. I was just thinking it would be great to have a deep dive into matching the properties of classic controls (such as "outerShadow"), and how to implement them in Extension Builder language.

**Comment by macMikey** [comment]
by all means add this as an issue or a page in the wiki and let's see where it leads.
